#!/usr/bin/env bash

. ./lib/bmp || exit

main() {
	local width=2
	local height=2

	bmp_header "$width" "$height"

	local padding=$REPLY

	# Color Data
	rgb 0 0 0
	rgb 255 255 255
	bmp_padding "$padding"

	rgb 255 0 0
	rgb 0 255 0
	bmp_padding "$padding"
}

main "$@"
